# Generated by Django 4.2 on 2023-12-28 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='cvc',
            field=models.IntegerField(),
        ),
    ]
