# Generated by Django 4.2 on 2023-12-28 11:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='ID', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Updated At')),
                ('deleted', models.BooleanField(default=False)),
                ('account_number', models.CharField(max_length=255, unique=True)),
                ('account_type', models.CharField(choices=[('deposit', 'Deposit'), ('credit', 'Credit'), ('debit', 'Debit'), ('consumer', 'Consumer')])),
                ('balance', models.DecimalField(decimal_places=2, max_digits=20)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
